server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: '*'
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: vehiculos
          uri: lb://vehiculos
          predicates:
            - Path=/vehiculo/**
        - id: reparaciones
          uri: lb://reparaciones
          predicates:
            - Path=/reparacion/**