server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehiculos
          uri: lb://vehiculos
          predicates:
            - path=/vehiculo/**
        - id: reparaciones
          uri: lb://reparaciones
          predicates:
            - path=/reparacion/**