server:
  port: 8013
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/listaReparaciones
    username: postgres
    password: 1501
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}