apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_VEHICULOS: cG9zdGdyZXM=
  DB_PASSWORD_VEHICULOS: cG9zdGdyZXM=
  DB_USER_REPARACIONES: cG9zdGdyZXM=
  DB_PASSWORD_REPARACIONES: cG9zdGdyZXM=