server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/MatiasAravena/e2_tingeso2024.git
          search-paths: config-data
  application:
    name: config-service